
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Oct  1 2025 10:16:51 IST (Oct  1 2025 04:46:51 UTC)

// Verification Directory fv/ksa16 

module ksa16(clock, reset, a, b, cin, sum, carryout);
  input clock, reset, cin;
  input [15:0] a, b;
  output [15:0] sum;
  output carryout;
  wire clock, reset, cin;
  wire [15:0] a, b;
  wire [15:0] sum;
  wire carryout;
  wire n_0, n_1, n_4, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_38, n_39, n_40, n_41, n_42;
  wire n_43, n_44, n_45, n_46, n_47, n_83, n_84;
  DFKCNQD1 carryout_reg(.CP (clock), .CN (n_47), .D (n_45), .Q
       (carryout));
  DFKCNQD1 \sum_reg[15] (.CP (clock), .CN (n_47), .D (n_46), .Q
       (sum[15]));
  CKXOR2D0 g2631__2398(.A1 (n_44), .A2 (n_43), .Z (n_46));
  AO22D0 g2630__5107(.A1 (n_44), .A2 (n_43), .B1 (b[15]), .B2 (a[15]),
       .Z (n_45));
  DFKCNQD1 \sum_reg[14] (.CP (clock), .CN (n_47), .D (n_42), .Q
       (sum[14]));
  CKXOR2D0 g2634__6260(.A1 (n_41), .A2 (n_40), .Z (n_42));
  DFKCNQD1 \sum_reg[13] (.CP (clock), .CN (n_47), .D (n_39), .Q
       (sum[13]));
  AO22D0 g2633__4319(.A1 (n_41), .A2 (n_40), .B1 (b[14]), .B2 (a[14]),
       .Z (n_44));
  CKXOR2D0 g2637__8428(.A1 (n_38), .A2 (n_37), .Z (n_39));
  DFKCNQD1 \sum_reg[12] (.CP (clock), .CN (n_47), .D (n_36), .Q
       (sum[12]));
  AO22D0 g2636__5526(.A1 (n_38), .A2 (n_37), .B1 (b[13]), .B2 (a[13]),
       .Z (n_41));
  AO22D0 g2639__6783(.A1 (n_35), .A2 (n_34), .B1 (b[12]), .B2 (a[12]),
       .Z (n_38));
  DFKCNQD1 \sum_reg[11] (.CP (clock), .CN (n_47), .D (n_33), .Q
       (sum[11]));
  CKXOR2D0 g2640__3680(.A1 (n_35), .A2 (n_34), .Z (n_36));
  DFKCNQD1 \sum_reg[10] (.CP (clock), .CN (n_47), .D (n_30), .Q
       (sum[10]));
  CKXOR2D0 g2643__1617(.A1 (n_32), .A2 (n_31), .Z (n_33));
  AO22D0 g2642__2802(.A1 (n_32), .A2 (n_31), .B1 (b[11]), .B2 (a[11]),
       .Z (n_35));
  AO22D0 g2645__1705(.A1 (n_29), .A2 (n_28), .B1 (b[10]), .B2 (a[10]),
       .Z (n_32));
  CKXOR2D0 g2646__5122(.A1 (n_29), .A2 (n_28), .Z (n_30));
  DFKCNQD1 \sum_reg[9] (.CP (clock), .CN (n_47), .D (n_27), .Q
       (sum[9]));
  AO22D0 g2648__8246(.A1 (n_26), .A2 (n_25), .B1 (b[9]), .B2 (a[9]), .Z
       (n_29));
  CKXOR2D0 g2649__7098(.A1 (n_26), .A2 (n_25), .Z (n_27));
  DFKCNQD1 \sum_reg[8] (.CP (clock), .CN (n_47), .D (n_24), .Q
       (sum[8]));
  DFKCNQD1 \sum_reg[7] (.CP (clock), .CN (n_47), .D (n_21), .Q
       (sum[7]));
  CKXOR2D0 g2652__6131(.A1 (n_23), .A2 (n_22), .Z (n_24));
  AO22D0 g2651__1881(.A1 (n_23), .A2 (n_22), .B1 (b[8]), .B2 (a[8]), .Z
       (n_26));
  DFKCNQD1 \sum_reg[6] (.CP (clock), .CN (n_47), .D (n_18), .Q
       (sum[6]));
  CKXOR2D0 g2655__5115(.A1 (n_20), .A2 (n_19), .Z (n_21));
  AO22D0 g2654__7482(.A1 (n_20), .A2 (n_19), .B1 (b[7]), .B2 (a[7]), .Z
       (n_23));
  DFKCNQD1 \sum_reg[5] (.CP (clock), .CN (n_47), .D (n_15), .Q
       (sum[5]));
  CKXOR2D0 g2658__4733(.A1 (n_17), .A2 (n_16), .Z (n_18));
  AO22D0 g2657__6161(.A1 (n_17), .A2 (n_16), .B1 (b[6]), .B2 (a[6]), .Z
       (n_20));
  AO22D0 g2660__9315(.A1 (n_14), .A2 (n_13), .B1 (b[5]), .B2 (a[5]), .Z
       (n_17));
  CKXOR2D0 g2661__9945(.A1 (n_14), .A2 (n_13), .Z (n_15));
  DFKCNQD1 \sum_reg[4] (.CP (clock), .CN (n_47), .D (n_12), .Q
       (sum[4]));
  AO22D0 g2663__2883(.A1 (n_11), .A2 (n_10), .B1 (b[4]), .B2 (a[4]), .Z
       (n_14));
  CKXOR2D0 g2664__2346(.A1 (n_11), .A2 (n_10), .Z (n_12));
  DFKCNQD1 \sum_reg[3] (.CP (clock), .CN (n_47), .D (n_9), .Q (sum[3]));
  AO22D0 g2666__1666(.A1 (n_8), .A2 (n_7), .B1 (b[3]), .B2 (a[3]), .Z
       (n_11));
  CKXOR2D0 g2667__7410(.A1 (n_8), .A2 (n_7), .Z (n_9));
  DFKCNQD1 \sum_reg[2] (.CP (clock), .CN (n_47), .D (n_6), .Q (sum[2]));
  AO22D0 g2669__6417(.A1 (n_83), .A2 (n_4), .B1 (b[2]), .B2 (a[2]), .Z
       (n_8));
  CKXOR2D0 g2670__5477(.A1 (n_83), .A2 (n_4), .Z (n_6));
  DFKCNQD1 \sum_reg[1] (.CP (clock), .CN (n_47), .D (n_84), .Q
       (sum[1]));
  DFKCNQD1 \sum_reg[0] (.CP (clock), .CN (n_47), .D (n_0), .Q (sum[0]));
  XOR3D0 g2675__6260(.A1 (a[0]), .A2 (b[0]), .A3 (cin), .Z (n_0));
  CKXOR2D0 g2677__4319(.A1 (a[2]), .A2 (b[2]), .Z (n_4));
  CKXOR2D0 g2687__8428(.A1 (a[7]), .A2 (b[7]), .Z (n_19));
  CKXOR2D0 g2688__5526(.A1 (a[8]), .A2 (b[8]), .Z (n_22));
  CKXOR2D0 g2689__6783(.A1 (a[4]), .A2 (b[4]), .Z (n_10));
  CKXOR2D0 g2690__3680(.A1 (a[14]), .A2 (b[14]), .Z (n_40));
  CKXOR2D0 g2676__1617(.A1 (a[10]), .A2 (b[10]), .Z (n_28));
  CKXOR2D0 g2686__2802(.A1 (a[15]), .A2 (b[15]), .Z (n_43));
  CKXOR2D0 g2682__1705(.A1 (a[3]), .A2 (b[3]), .Z (n_7));
  CKXOR2D0 g2680__8246(.A1 (a[12]), .A2 (b[12]), .Z (n_34));
  CKXOR2D0 g2681__7098(.A1 (a[11]), .A2 (b[11]), .Z (n_31));
  CKXOR2D0 g2678__6131(.A1 (a[13]), .A2 (b[13]), .Z (n_37));
  CKXOR2D0 g2683__1881(.A1 (a[5]), .A2 (b[5]), .Z (n_13));
  CKXOR2D0 g2684__5115(.A1 (a[6]), .A2 (b[6]), .Z (n_16));
  CKXOR2D0 g2685__7482(.A1 (a[9]), .A2 (b[9]), .Z (n_25));
  CKAN2D1 g2691__4733(.A1 (a[0]), .A2 (b[0]), .Z (n_1));
  CKND1 g2692(.I (reset), .ZN (n_47));
  FA1D0 g2710(.A (a[1]), .B (b[1]), .CI (n_1), .CO (n_83), .S (n_84));
endmodule

